# Generated by Django 5.1.6 on 2025-02-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_productdb_remove_categorydb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='sub_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
