# Generated by Django 5.1.6 on 2025-02-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_cad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaD',
        ),
    ]
