# Generated by Django 5.1.6 on 2025-02-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_delete_cad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, unique=True)),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='Design Category')),
            ],
        ),
        migrations.CreateModel(
            name='DesignsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Style', models.CharField(blank=True, max_length=50, null=True)),
                ('Dimension', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Interior Designs')),
                ('Estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
