# Generated by Django 5.1.6 on 2025-03-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_designsdb_designer'),
        ('DesignApp', '0003_consultdb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgressDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('WorkImage', models.ImageField(blank=True, null=True, upload_to='Working progress')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DesignApp.consultdb')),
            ],
        ),
    ]
