# Generated by Django 5.1.6 on 2025-03-20 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_trackingdb'),
        ('WebApp', '0009_ordertracking_user_name_paymentdetails_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdb',
            name='paymnet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.ordertracking'),
            preserve_default=False,
        ),
    ]
