# Generated by Django 5.1.6 on 2025-03-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_trackingdb_paymnet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingdb',
            old_name='paymnet',
            new_name='payment',
        ),
    ]
