# Generated by Django 5.1.6 on 2025-02-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_contactdb_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='Project',
            new_name='Message',
        ),
    ]
