# Generated by Django 5.1.6 on 2025-03-18 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_paymentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_status', models.CharField(default='Payment Successful', max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.orderdb')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.paymentdetails')),
            ],
        ),
    ]
