# Generated by Django 5.1.6 on 2025-03-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
