# Generated by Django 5.1.6 on 2025-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('design_id', models.IntegerField(unique=True)),
                ('design_category', models.CharField(max_length=100)),
                ('design_name', models.CharField(max_length=100)),
                ('design_estimate', models.IntegerField()),
                ('design_dimension', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
