# Generated by Django 5.1.6 on 2025-03-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignApp', '0002_alter_consultdb_design_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultdb',
            name='status',
            field=models.CharField(choices=[('consult', 'Consult'), ('booked', 'Booked'), ('completed', 'Completed')], default='consult', max_length=10),
        ),
    ]
