# Generated by Django 5.1.6 on 2025-03-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignApp', '0004_consultdb_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultdb',
            name='user',
        ),
        migrations.AddField(
            model_name='consultdb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
