# Generated by Django 5.1.6 on 2025-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignApp', '0005_remove_consultdb_user_consultdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultdb',
            name='design_id',
            field=models.IntegerField(),
        ),
    ]
